server:
  port: 80
  
ribbon:
  eureka:
    enabled: true       #开启负载均衡
    
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver9001.com:9001/eureka/ #,http://eurekasever9002.com:9002/eureka,http://eurekasever9003.com:9003/eureka

info:
  app.name: SpringCloud
  author: zyh
  message: this product is get product info
  
spring:
  application:
    name: woniu58-consumer-feign
    
feign:  hystrix:    enabled: true #开启服务降级