server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver9001.com:9001/eureka/ #,http://eurekaserver9002.com:9002/eureka/, http://eurekaserver9003.com:9003/eureka/
  instance:
    instance-id: woniu58-consumer-8080  #配置中心中显示微服务的名称
    prefer-ip-address: true  #是否显示访问微服务的url
    
info:
  app.name: SpringCloud58
  auther: zyh
  message: this product is get product info